name: Docker Image CI

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    ‐ name: build
        id: build
        uses: docker/build-action@v1
        with:
          repository: tommilehtisaari/digiroad-privateroad-backend
    ‐ name: login
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    ‐ name: push
      uses: docker/push-action@v1
      with:
        registry: digiroad-privateroad-backend
        tags: ${{ github.sha }}
