name: Docker Image CI

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      ‐ name: build-push
        uses: docker/build-push-action@v1
        with:
          username: ${{ DOCKER_USERNAME }}
          password: ${{ DOCKER_PASSWORD }}
          registry: docker.io
          repository: tommilehtisaari/digiroad-privateroad-backend
          tags: v1
